/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewsItem {
  'id' : bigint,
  'title' : string,
  'source' : string,
  'date' : Time,
  'description' : string,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'totalScore' : bigint,
  'testsAttempted' : bigint,
}
export interface UserProgress {
  'lastCompletedDate' : Time,
  'totalDaysInProgram' : bigint,
  'totalDaysCompleted' : bigint,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalScore' : bigint,
  'testsAttempted' : bigint,
  'accuracy' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNewsItem' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllNewsItems' : ActorMethod<[], Array<NewsItem>>,
  'getAllNewsItemsByDate' : ActorMethod<[], Array<NewsItem>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyStats' : ActorMethod<[], UserStats>,
  'getNewsItem' : ActorMethod<[bigint], NewsItem>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'incrementTestsAttempted' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDayCompleted' : ActorMethod<[], undefined>,
  'prepopulateNewsItems' : ActorMethod<[], undefined>,
  'saveProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];