/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const NewsItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'totalScore' : IDL.Nat,
  'testsAttempted' : IDL.Nat,
});
export const UserStats = IDL.Record({
  'totalScore' : IDL.Nat,
  'testsAttempted' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const UserProgress = IDL.Record({
  'lastCompletedDate' : Time,
  'totalDaysInProgram' : IDL.Nat,
  'totalDaysCompleted' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNewsItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getAllNewsItemsByDate' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyStats' : IDL.Func([], [UserStats], ['query']),
  'getNewsItem' : IDL.Func([IDL.Nat], [NewsItem], ['query']),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'incrementTestsAttempted' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markDayCompleted' : IDL.Func([], [], []),
  'prepopulateNewsItems' : IDL.Func([], [], []),
  'saveProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const NewsItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'totalScore' : IDL.Nat,
    'testsAttempted' : IDL.Nat,
  });
  const UserStats = IDL.Record({
    'totalScore' : IDL.Nat,
    'testsAttempted' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const UserProgress = IDL.Record({
    'lastCompletedDate' : Time,
    'totalDaysInProgram' : IDL.Nat,
    'totalDaysCompleted' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNewsItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getAllNewsItemsByDate' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyStats' : IDL.Func([], [UserStats], ['query']),
    'getNewsItem' : IDL.Func([IDL.Nat], [NewsItem], ['query']),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'incrementTestsAttempted' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markDayCompleted' : IDL.Func([], [], []),
    'prepopulateNewsItems' : IDL.Func([], [], []),
    'saveProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };